# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
# orbs:
#   aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.17.11 # circleci/golang:1.12.5
    environment: GO111MODULE=on
    steps:
      - checkout
      - run:
          name: Install Gomason
          command: go get github.com/nikogura/gomason
      - run:
          name: Initialize GPG Agent
          command: gpg-agent --daemon
      - run:
          name: Install Vault
          command: |
            wget https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_linux_amd64.zip
            unzip vault_1.4.0_linux_amd64.zip
            sudo mv vault /usr/local/bin
      - run:
          name: Run Tests
          command: gomason test -v -b ${CIRCLE_BRANCH}

  publish:
    docker:
      - image: cimg/go:1.17.11 # circleci/golang:1.12.5
    environment: GO111MODULE=on
    steps:
      - checkout
      - run:
          name: Install Gomason
          command: go get github.com/nikogura/gomason
      - run:
          name: Initialize GPG Agent
          command: gpg-agent --daemon
      - run:
          name: Install Vault
          command: |
            wget https://releases.hashicorp.com/vault/1.4.0/vault_1.4.0_linux_amd64.zip
            unzip vault_1.4.0_linux_amd64.zip
            sudo mv vault /usr/local/bin
      - run:
          name: Stage Signing Key
          command: |
            echo "$SIGNING_PRIVATE_KEY" | base64 -d > obci@orionlabs.asc
      - run:
          name: Import Signing Key
          command: gpg --import obci@orionlabs.asc
      - run:
          name: Publish
          command: gomason publish -v

workflows:
  version: 2
  primary:
    jobs:
      - test:
          context:
            - AWS-COMMON
            # - AWS-CIRCLECI
          filters:
            branches:
              ignore:
                - master
      - publish:
          context:
            - AWS-COMMON
            # - AWS-CIRCLECI
          filters:
            branches:
              only:
                - master
